version:   "3.1"

services:
  postgres :
    container_name: postgres-ecomgraphql
    image:
      postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passer123
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    container_name: pgadmin-ecomgraphql
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
volumes:
  data:

