spring:
  datasource:
    username: postgres
    password: passer123
    url:  jdbc:postgresql://localhost:5432/ecommerce-grapqhl
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  #enable graphQL for testing

  graphql:
    graphiql:
      enabled: true
  mail:
    host: localhost
    port: 9025
    protocol: smtp
  security:
    user:
      name: mouhamedniang@groupeisi.com
      password: collision@24